In [1]:
import os
import pandas
 
DATA = pandas.read_csv("Data.csv")

DATA

,temp,hum,windspeed,cnt,season_1,season_2,season_3,season_4,yr_0,yr_1,...,mnth_5,mnth_6,mnth_7,mnth_8,mnth_9,weathersit_1,weathersit_2,weathersit_3,holiday_0,holiday_1
0,0.344167,0.805833,0.160446,985,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0.363478,0.696087,0.248539,801,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
2,0.196364,0.437273,0.248309,1349,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
3,0.200000,0.590435,0.160296,1562,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
4,0.226957,0.436957,0.186900,1600,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,0.254167,0.652917,0.350133,2114,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
713,0.253333,0.590000,0.155471,3095,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
714,0.253333,0.752917,0.124383,1341,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
715,0.255833,0.483333,0.350754,1796,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,1,0
716,0.215833,0.577500,0.154846,2729,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0

In [2]:
# Separating the depenedent and independent data variables into two dataframes.
from sklearn.model_selection import train_test_split 
X = DATA.drop(['cnt'],axis=1) # use others as inputs for prediction
Y = DATA['cnt'] # set cnt as output for prediction

type(X)

Y

0       985
1       801
2      1349
3      1562
4      1600
       ...
712    2114
713    3095
714    1341
715    1796
716    2729
Name: cnt, Length: 717, dtype: int64

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.20, random_state=0)

X_train

,temp,hum,windspeed,season_1,season_2,season_3,season_4,yr_0,yr_1,mnth_1,...,mnth_5,mnth_6,mnth_7,mnth_8,mnth_9,weathersit_1,weathersit_2,weathersit_3,holiday_0,holiday_1
683,0.291667,0.786667,0.237562,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,1,0
17,0.216667,0.861667,0.146775,1,0,0,0,1,0,1,...,0,0,0,0,0,0,1,0,1,0
266,0.616667,0.699167,0.172883,0,0,0,1,1,0,0,...,0,0,0,0,1,1,0,0,1,0
318,0.447500,0.910000,0.138054,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1,1,0
364,0.334167,0.542083,0.167908,1,0,0,0,0,1,1,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,0.326667,0.556667,0.374383,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
192,0.719167,0.604167,0.245033,0,0,1,0,1,0,0,...,0,0,1,0,0,1,0,0,1,0
629,0.657500,0.793750,0.066546,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,1,0
559,0.724167,0.450000,0.164800,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0
684,0.296667,0.506250,0.210821,0,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,1,0

In [4]:
from sklearn.linear_model import Lasso
lasso_model = Lasso(alpha = 1.0) # set penalty value
lasso = lasso_model.fit(X_train , Y_train)
lasso_predict = lasso.predict(X_test)

In [5]:
import numpy as np
error = np.mean(np.abs((Y_test - lasso_predict)))
print('error is', error)

error is 547.2374740881395

In [6]:
# Mean absolute percentage error

import numpy as np
def MAPE(Y_actual,Y_Predicted):
    mape = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
    return mape

In [7]:
Lasso_MAPE = MAPE(Y_test,lasso_predict)
print("MAPE value: ",Lasso_MAPE)

MAPE value:  16.55305612241603

In [8]:
Accuracy = 100 - Lasso_MAPE
print('Accuracy of Lasso Regression: {:0.2f}%.'.format(Accuracy))

Accuracy of Lasso Regression: 83.45%.